stages:
  extract:
    cmd: python src/pipelines/extract.py
    deps:
    - src/pipelines/extract.py
    params:
    - extract.end_year
    - extract.output_path
    - extract.start_year
    outs:
    - data/raw/:
        persist: true
  combine:
    cmd: python src/pipelines/combine.py
    deps:
    - data/raw/
    - src/pipelines/combine.py
    params:
    - combine.end_year
    - combine.file_name
    - combine.input_path
    - combine.output_path
    - combine.start_year
    outs:
    - data/combined/:
        persist: true
  transform:
    cmd: python src/pipelines/transform.py
    deps:
    - data/combined/
    - src/pipelines/transform.py
    params:
    - transform.input_path
    - transform.outlier_lap_time_percentage
    - transform.output_path
    outs:
    - data/processed/processed_data.csv:
        persist: true

  # --- NEW STAGE FOR PIT STOP PIPELINE ---
  transform_pitstops:
    cmd: python src/pipelines/transform_pitstops.py
    deps:
      - data/combined/all_laps.csv
      - src/pipelines/transform_pitstops.py
    params:
      - transform_pitstops.input_path
      - transform_pitstops.output_path
      - transform_pitstops.min_pit_delta
    outs:
      - data/processed/pit_stop_data.csv:
          persist: true
