# This is a copy of the backend's track_config.yaml.
# It's used by the frontend to populate UI elements without needing an API call.
default:
  air_temp: 22.0
  track_temp: 32.0
  pit_stop_time: 23.0
  total_laps: 55

tracks:
  Melbourne:
    air_temp: 20.0
    track_temp: 35.0
    pit_stop_time: 21.5
    total_laps: 58
  Shanghai:
    air_temp: 22.0
    track_temp: 38.0
    pit_stop_time: 23.5
    total_laps: 56
  Suzuka:
    air_temp: 18.0
    track_temp: 28.0
    pit_stop_time: 23.0
    total_laps: 53
  Bahrain:
    air_temp: 28.0
    track_temp: 35.0
    pit_stop_time: 22.5
    total_laps: 57
  Jeddah:
    air_temp: 26.0
    track_temp: 32.0
    pit_stop_time: 21.0
    total_laps: 50
  Miami:
    air_temp: 29.0
    track_temp: 45.0
    pit_stop_time: 22.0
    total_laps: 57
  Imola:
    air_temp: 20.0
    track_temp: 40.0
    pit_stop_time: 28.0
    total_laps: 63
  Monaco:
    air_temp: 24.0
    track_temp: 45.0
    pit_stop_time: 20.5
    total_laps: 78
  "Circuit de Barcelona-Catalunya":
    air_temp: 26.0
    track_temp: 44.0
    pit_stop_time: 22.2
    total_laps: 66
  Montreal:
    air_temp: 19.0
    track_temp: 33.0
    pit_stop_time: 18.5
    total_laps: 70
  Spielberg:
    air_temp: 22.0
    track_temp: 42.0
    pit_stop_time: 19.5
    total_laps: 71
  Silverstone:
    air_temp: 20.0
    track_temp: 30.0
    pit_stop_time: 24.5
    total_laps: 52
  "Spa-Francorchamps":
    air_temp: 18.0
    track_temp: 25.0
    pit_stop_time: 21.5
    total_laps: 44
  Budapest:
    air_temp: 28.0
    track_temp: 50.0
    pit_stop_time: 20.0
    total_laps: 70
  Zandvoort:
    air_temp: 20.0
    track_temp: 35.0
    pit_stop_time: 21.0
    total_laps: 72
  Monza:
    air_temp: 25.0
    track_temp: 40.0
    pit_stop_time: 24.0
    total_laps: 53
  Baku:
    air_temp: 24.0
    track_temp: 48.0
    pit_stop_time: 22.0
    total_laps: 51
  Singapore:
    air_temp: 29.0
    track_temp: 36.0
    pit_stop_time: 25.0
    total_laps: 62
  Austin:
    air_temp: 27.0
    track_temp: 38.0
    pit_stop_time: 21.8
    total_laps: 56
  "Mexico City":
    air_temp: 22.0
    track_temp: 46.0
    pit_stop_time: 20.0
    total_laps: 71
  "Sao Paulo":
    air_temp: 21.0
    track_temp: 40.0
    pit_stop_time: 21.2
    total_laps: 71
  "Las Vegas":
    air_temp: 15.0
    track_temp: 18.0
    pit_stop_time: 22.5
    total_laps: 50
  Lusail:
    air_temp: 30.0
    track_temp: 36.0
    pit_stop_time: 20.5
    total_laps: 57
  "Yas Marina":
    air_temp: 28.0
    track_temp: 34.0
    pit_stop_time: 22.8
    total_laps: 58
